spring:
  profiles: local
  datasource:
    username: root
    password: 18651865
    jdbcUrl: jdbc:mysql://localhost:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
horus:
  nlp:
    pv:
      train:
        root: /Users/a1000074/dev/temp-dl/train/
        up-dir: /Users/a1000074/dev/temp-dl/train/up/
        down-dir: /Users/a1000074/dev/temp-dl/train/down/
      test:
        root: /Users/a1000074/dev/temp-dl/test/
logging:
  config: classpath:logback-spring.xml
---
spring:
  profiles: localhome
  datasource:
    username: root
    password: root
    jdbcUrl: jdbc:mysql://studio:3306/horus?useUnicode=true&characterEncoding=utf8useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://studio:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
horus:
  nlp:
    pv:
      train:
        root: /home/jeff/dev/temp-dl/train/
        up-dir: /home/jeff/dev/temp-dl/train/up/
        down-dir: /home/jeff/dev/temp-dl/train/down/
      test:
        root: home/jeff/dev/temp-dl/test/
        up-dir: /home/jeff/dev/temp-dl/test/up/
        down-dir: /home/jeff/dev/temp-dl/test/down/
logging:
  config: classpath:logback-spring.xml
---
spring:
  profiles: homeStudio
  datasource:
    username: root
    password: root
    jdbcUrl: jdbc:mysql://mysql8:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysql8:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
horus:
  nlp:
    pv:
      train:
        root: /home/jeff/dev/temp-dl/train/
        up-dir: /home/jeff/dev/temp-dl/train/up/
        down-dir: /home/jeff/dev/temp-dl/train/down/
      test:
        root: home/jeff/dev/temp-dl/test/
        up-dir: /home/jeff/dev/temp-dl/test/up/
        down-dir: /home/jeff/dev/temp-dl/test/down/
logging:
  config: classpath:logback-spring.xml