spring:
  profiles: local
  datasource:
    username: root
    password: 18651865
    jdbcUrl: jdbc:mysql://localhost:3306/horus?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/horus?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
logging:
  config: classpath:logback-spring.xml
---
spring:
  profiles: localhome
  datasource:
    username: root
    password: 1999
    jdbcUrl: jdbc:mysql://localhost:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://localhost:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
logging:
  config: classpath:logback-spring.xml